#! /bin/bash

## TODO: Find a better way to know we are running from the correct place.
prelude_expected_sha="e0eeb7d7ccb8fb3aeed2abbff0847c495aaca82a69750a051cfbcfc557da0034"
prelude_sha=$(sha256sum prelude | cut -d' ' -f 1)
if [[ "$prelude_expected_sha" != "$prelude_sha" ]]; then
  echo "Something is off!"
  exit 1
fi

## Store the root
vsr_root=$(pwd)

## Installing is trivial, just add a couple lines to the beginning of
## our profile skeleton file:
profile_prefix="#! /bin/bash\nVSR_ROOT=$vsr_root\nexport VSR_ROOT\n"
echo -e "$profile_prefix" | cat - "$vsr_root/config/bash/profile" > temp \
  && mv temp "$HOME/.profile" \
  && ln -fs "$vsr_root/config/bash/bashrc_default" "$HOME/.bashrc"

## Link our unison profiles; we create a dedicated directory because unison loves
## to keep some of its own local control files in there, so better not pollute
## vsr with it.
mkdir -p "$HOME/.unison" \
  && ln -fs $vsr_root/config/unison/* "$HOME/.unison/"

## Link SSH config file
mkdir -p "$HOME/.ssh" \
  && chmod 700 "$HOME/.ssh" \
  && ln -fs $vsr_root/config/ssh/config "$HOME/.ssh/config"

## Link our XMonad directory but does not install it just yet; that
## installation should be done manually after the system is up and running
ln -fs $vsr_root/config/xmonad "$HOME/.xmonad"

## Link our vim directory file
ln -fs $vsr_root/config/vim "$HOME/.vim"

## Link our user directories
ln -fs $vsr_root/config/xdg/user-dirs.dirs "$HOME/.config/user-dirs.dirs"

## Link our templates
ln -fs $vsr_root/config/templates "$HOME/.templates"

## Link our vifm config
ln -fs $vsr_root/config/vifm "$HOME/.vifm"

## Link our papis config
mkdir -p "$HOME/.config"
ln -fs $vsr_root/config/papis "$HOME/.config/papis"

## Setup our base directory structure
mydirs=("$HOME/tmp/Desktop"
        "$HOME/data/Music"
        "$HOME/data/Videos"
        "$HOME/data/Pictures"
        "$HOME/keychain"
        "$HOME/repos"
        "$HOME/doc"
        "$HOME/bin")
 
for d in ${mydirs[*]}; do
   if [[ ! -d "$d" ]]; then
       mkdir -p "$d"
   fi
done

rmdirs=("$HOME/Music"
        "$HOME/Documents"
        "$HOME/Downloads"
        "$HOME/Public"
        "$HOME/Templates"
        "$HOME/Pictures"
        "$HOME/Desktop"
        "$HOME/Videos")

for d in ${rmdirs[*]}; do
  if [[ -d "$d" ]]; then
    rmdir "$d"
  fi
done
