#! /bin/bash

#vsr_root="${BASH_SOURCE%/*}"
vsr_root="$VSR_ROOT"

# Completion function for vsr.
# Imagine we are typing:
#
#   vsr apt pkg-[TAB]
#
function _vsr_complete_()
{
  # word will be "pkg-", but "COMP_WORDS" is the
  # array ( "vsr" "apt" "pkg-" )
  local word=${COMP_WORDS[COMP_CWORD]}

  # We then just go inside the necessary folder,
  local path="$vsr_root/scripts"
  local i=1
  while [ $i -lt $COMP_CWORD ]; do
    path="$path/${COMP_WORDS[$i]}"
    i=$((i + 1))
  done

  # Get its contents,
  local opts=""

  # If the path is accesible, list its contents as
  # a completion.
  if [[ -d "$path" ]]; then
    opts=$(ls -1 $path)
    # And complete accordingly!
    COMPREPLY=( $(compgen -W "${opts}" -X "*~" -- "${word}" ) )
  # Otherwise, complete using current dirs filenames.
  else
    COMPREPLY=( $(compgen -f -X "*~" -- "${word}") )
  fi
}

complete -F _vsr_complete_ vsr
