#! /bin/bash

vsr_root="${BASH_SOURCE%/*}/../.."
source "$vsr_root/scripts/prelude"

if [[ "$#" -ne "1" ]]; then exit 1; fi
if [ ! -e "$1" ]; then exit 1; fi

dst="$1"

echo "!! WARNING !!"
echo "   Will copy in PLAINTEXT"
echo "Backing up ~/usr/keychain and ~/usr/priv to $dst"
echo ""
read -p "  continue? (type yes) " ans
case "$ans" in
  [Yy]es)
    vsr sys folder-mirror usr/keychain $dst 
    vsr sys folder-mirror usr/priv $dst 
  ;;
esac
