#! /bin/bash

# Adding some colors is a cool idea
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
# And fixing up my hostname at the window title
PROMPT_COMMAND='echo -ne "\033]0;"Bash $(whoami)@$(hostname)"\007"'

# Cool weather forecast in the terminal
alias weather='curl -4 http://wttr.in/Utrecht'
