#! /bin/bash

### GNUPG Home Directory
GNUPGHOME="$HOME/usr/keychain/gnupg"
export GNUPGHOME

KEYCHAIN_ROOT=CB4A4FBA
export KEYCHAIN_ROOT

### Pass Password store dir
PASSWORD_STORE_DIR="$HOME/usr/keychain/password-store"
export PASSWORD_STORE_DIR

### Our latex library
LATEXLIB=$HOME/lib/latex
export LATEXLIB

### Modify our path
PATH=$HOME/.local/bin:$HOME/bin:$HOME/.cabal/bin:$PATH
export PATH

### We like vim!
export EDITOR="vim"
