#! /bin/bash

function showUsage() {
  echo "ghc setversion [version]"
  echo ""
  echo "  Sets the version of ghc that user $(whoami) will use."
  echo "  If no argument is supplied, list all possible versions."
}

if (( $# > 1 )); then
  showUsage
  exit 1
elif (( $# == 0 )); then
  ls /opt/ghc
  exit 0
fi

VER="$1"
if [[ ! -d "/opt/ghc/$VER" ]]; then
  echo "Version $VER is not installed."
  echo "Here are the ones you have: "
  ls /opt/ghc
  exit 1
else
  DIR="/opt/ghc/$VER/bin"
  ln -sf "$DIR/ghc-$VER"      "$HOME/bin/ghc"
  ln -sf "$DIR/ghci-$VER"     "$HOME/bin/ghci"
  ln -sf "$DIR/ghc-pkg-$VER"  "$HOME/bin/ghc-pkg"
  ln -sf "$DIR/runghc-$VER"   "$HOME/bin/runhaskell"
fi
