alias nrc='nix shell -f default.nix -c'
alias restart-work-vpn='sudo systemctl restart wg-quick@wg-dev'
alias git-please='git push --force-with-lease'
alias cab-all='cabal build all --enable-tests --enable-benchmarks'

