#! /bin/bash

lock="/tmp/kbd-config-done"

if [[ -e "$lock" ]]; then
  echo "Keyboard is already modded!"
  echo ""
  echo "  if you really want to run again; delete $lock"
  echo ""
  exit 1
fi

# Addapted from xcape manual.

# Map an unused modifier's keysym to the return's keycode and make it a
# control modifier. It needs to be an existing key so that emacs won't
# spazz out when you press it. Hyper_L is a good candidate.
spare_modifier="Hyper_L"
xmodmap -e "keycode 36 = $spare_modifier"
xmodmap -e "remove mod4 = $spare_modifier" # hyper_l is mod4 by default
xmodmap -e "add Control = $spare_modifier"

# Map "Return" to an unused keycode (to keep it around for xcape to
# use).
xmodmap -e "keycode 250 = Return"

# Finally use xcape to cause the enter to generate a space when tapped.
xcape -e "$spare_modifier=Return"

#### Assigning Alt_R to Caps_Lock
## xmodmap -e "remove Lock = Caps_Lock" 
## xmodmap -e "keycode 66  = Alt_R" 

date +%d%m-%H%M > "$lock"
