#! /bin/bash

vsr_root="${BASH_SOURCE%/*}.."
source "$vsr_root/prelude"

function showHelp() {
  errcho "usage: pkg-maintain [opts]"
  errcho ""
  errcho "  pkg-maintain will maintain the packages on this system."
  errcho "  We shall read the list of packages to install and remove"
  errcho "  from config/packages."
  errcho ""
  errcho "  -v  --verbose   chatty output on stderr."
  errcho "  -h  --help      this screen."
  errcho "  -d  --dry-run   makes a dry-run (don't install or remove anything)."
  errcho "                  implies -v"
  errcho "  -u  --update    Update apt before doing changes."
}

verb=false
dryrun=false
update=false
while [[ $# -gt 0 ]]; do
  key=$1
  shift
  case $key in
    -v|--verbose)
      verb=true
    ;;
    
    -u|--update)
      update=true
    ;;

    -d|--dry-run)
      dryrun=true
    ;;

    *)
      showHelp
      exit 1
    ;;
  esac
done

# Makes sure we have the files we need!
uninstalls="$vsr_root/config/packages/uninstall"
installs="$vsr_root/config/packages/install"
if [[ ! -e $uninstalls ]] || [[ ! -e $installs ]]; then
  errcho "Package configuration files are missing."
  errcho "Aborting"
  return 1
fi 

# And we can sudo
sudo -k
errcho "I need sudo."
if ! sudo true; then
  errcho "Sorry, aborting."
  exit 1
fi

if $update; then
  sudo apt-get -qq update
  
  # Add GHC repo if it is not around.
  if [[ -z $(ls /etc/apt/sources.list.d/hvr*) ]]; then
    sudo add-apt-repository -y ppa:hvr/ghc
  fi
fi

# Handle uninstalls
(uncomment | while read line; do
  if pkg-is-installed "$line"; then
    if $dryrun; then
      errcho "sudo apt-get -y remove --purge \"$line\""
    else
      log-if "$verb" "Removing:   $line"
      sudo apt-get -y remove --purge "$line"
    fi
  fi
done) < "$uninstalls" 

# Remove errors from previous run, if any.
if [[ -e ./pkg-maintain-no-candidates ]]; then
  rm ./pkg-maintain-no-candidates
fi

# Handle installs
(uncomment | while read line; do
  if ! pkg-is-installed "$line"; then
    if pkg-has-candidate "$line"; then
      if $dryrun; then
        errcho "sudo apt-get -y install \"$line\""
      else
        log-if "$verb" "Installing: $line"
        sudo apt-get -y install "$line"
      fi 
    else
      echo "$line" >> pkg-maintain-no-candidates
    fi
  fi    
done) < "$installs" 

# This is a success if we didn't forget
# any package.
# shellcheck disable=SC2046
exit $(test ! -e ./pkg-maintain-no-candidates)
