#! /usr/bin/env bash
echo -en "\0prompt\x1f\n"
echo -en "\0no-custom\x1ftrue\n"
echo -en "\0message\x1fSelect password to copy, ESC to abort\n"
if [[ ! -z "$@" ]]; then
  bname=${@##*/}
  if [[ "$bname" == "2fa" ]]; then
    coproc { pass otp -c "$@"; notify-send "Copied 2FA code from '$@'"; }
  else
    coproc { pass -c "$@"; notify-send "Copied '$@'"; }
  fi
  exit 0
else
  find "$PASSWORD_STORE_DIR" -type f \
    | sed "s:$PASSWORD_STORE_DIR/::" | sed "s/\.gpg//"
fi

