#! /bin/bash

vsr_root="${BASH_SOURCE%/*}/../.."
source "$vsr_root/scripts/prelude"

function print_usage() {
  echo "usage: dav-bckp <dav> <dst>"
  echo ""
  echo "  Runs some rsync through our home and <dav>/<dst>"
  echo ""
  echo "    Make sure that <dav> is mounted"
  echo ""
  echo "    <dst> must be relative to the dav filesystem"
  echo ""
  exit 1
}

if [[ $# -lt 2 ]]; then
  print_usage
fi

case $1 in
  -h|--help)
    print_usage
  ;;
esac

## Nasty space-in-names problem.
dav="${1%%/}"
shift
dst="$@"
shift

ismounted=$(findmnt -lo target | grep "$dav")
if [[ -z "$ismounted" ]]; then
  echo "Error: $dav/$dst is not mounted!"
  exit 1
fi

final="$dav/$dst"

vsr sys myrsync --yes "usr/keychain" "$final/usr" --delete

