#! /bin/bash

vsr_root="${BASH_SOURCE%/*}/../.."
source "$vsr_root/scripts/prelude"

# Lets check whether or not ufw is managing IPV6 too:
IPV6=$(cat /etc/default/ufw | grep "IPV6=yes" | wc -l)
if [ "$IPV6" -ne 1 ]; then
  echo "WARNING: "
  echo "  ufw doesnt seem to be configuring IPv6"
  read -r -p "  Should we handle IPv6? [y/N] " response
  case $response in
      [yY]) 
          sed -i -- 's/IPV6=no/IPV6=yes/' /etc/default/ufw
          echo "  Done!"
          ;;
      *)
          echo "  Ok... :("
          ;;
  esac
fi

echo "Configuring UFW..."

# Default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# We're opening up ssh by default and thats it for now!
sudo ufw allow 22/tcp

sudo ufw enable


