#! /bin/bash

# So... unison is VERY picky with its versions. Not only all replicas
# must have the same version of unison, the binaries themselves must
# have been compiled with the same version of the OCaml compiler. 
# This is nuts and horrible!
#
# The best solution seems to be the one outline in: 
#   https://askubuntu.com/questions/1234767/can-i-install-unison-for-ubuntu-18-04-lts-on-ubuntu-20-04-lts
# Which is: purge current instalation everywhere, remove
# the .unison/{ar,fp}* cache files, donwload the Debian version
# on all replicas:
#
#  $ wget http://ftp.fr.debian.org/debian/pool/main/u/unison/unison_2.48.4-1+b1_amd64.deb
#  $ sudo dpkg -i unison_2.48.4-1+b1_amd64.deb
#
# finally, put unison on hold to defer upgrading the binary automagically
#
#  $ sudo apt-mark hold unison
#
# Yet, all the machines I'd like to sync are now running 20.04! Yay, no need for these dirty hacks!

vsr_root="${BASH_SOURCE%/*}/.."
source "$vsr_root/prelude"

function print_usage() {
  errcho "usage: vsr-unison [unison profile]"
  errcho ""
  errcho "  runs our magic unison, either on all"
  errcho "  proviles or on a single one"
  errcho ""
  exit 1
}

## The profiles that I like to enforce sync
allprofs=( "keychain" "doc" )

if [[ "$#" -eq "1" ]]; then
  allprofs=( "$1" )
elif [[ "$#" -gt "1" ]]; then
  print_usage
fi

remote_hostname="192.168.1.159"

local_root="/home/victor"
remote_root="ssh://$remote_hostname:$VSR_SSH_PORT//home/victor"
for prof in ${allprofs[*]}; do
  unison -perms 0 $prof -root "$local_root" -root "$remote_root"
done


