#! /bin/bash

vsr_root="${BASH_SOURCE%/*}/.."
source "$vsr_root/prelude"

function print_usage() {
  errcho "usage: vsr-bckp <dst> <additional rsync opts>"
  errcho ""
  errcho "    <dst> is the absolute path of the"
  errcho "          destination"
  exit 1
}

if [[ $# -lt 1 ]]; then
  print_usage
fi

dst="$1"
shift

case $dst in
  -h|--help)
    print_usage
  ;;
esac

echo "  SYSBCKP"
echo "  ======="
echo ""
echo "Starting interactive system backup."

if [ ! -e "$dst" ]; then
  errcho " !! Sorry, $dst does not exist"
  exit 1
fi

echo "By default, the following folders will be"
echo "copied to $dst."
echo ""
echo "    ~/bin"
echo ""
read -p "Should I copy ~/data (y/n) ? " ansUsrData
read -p "Should I copy ~/keychain and ~/doc  (y/n) ? " ansPriv

CPYDATA=false
CPYPRIV=false

case $ansUsrData in
  [Yy])
    CPYDATA=true
  ;;
esac

case $ansPriv in
  [Yy])
    CPYPRIV=true
  ;;
esac

echo ""
if $CPYDATA; then echo "I am copying your data."; fi
if $CPYPRIV; then echo "I am copying your private data."; fi

read -p "Last call... continue (y/n) ? " ans
case $ans in
  [Nn])
    echo "  ok... :/"
    exit 1
  ;;
esac

vsr-rsync --yes "bin"     "$dst"     --delete "$@"

if $CPYPRIV; then
  vsr-rsync --yes "keychain" "$dst" --delete "$@"
  vsr-rsync --yes "doc"      "$dst" --delete "$@"
fi

if $CPYDATA; then
  vsr-rsync --yes "data"     "$dst" "$@"
fi

