#! /bin/bash

# Lets check whether or not ufw is managing IPV6 too:
IPV6=$(cat /etc/default/ufw | grep "IPV6=yes" | wc -l)
if [ "$IPV6" -ne 1 ]; then
  echo "WARNING: "
  echo "  ufw doesnt seem to be configuring IPv6"
  read -r -p "  Should we handle IPv6? [y/N] " response
  case $response in
      [yY]) 
          sed -i -- 's/IPV6=no/IPV6=yes/' /etc/default/ufw
          echo "  Done!"
          ;;
      *)
          echo "  Ok... :("
          ;;
  esac
fi

echo "Configuring UFW..."

# Default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow from lan  machine to ssh into here when on my local network.
sudo ufw allow from 192.168.1.0/24 to any port $VSR_SSH_PORT

sudo ufw enable


