#! /bin/bash

# First, we pull changes from the tablet
$VSR_ROOT/config/android/adb-sync -R storage/self/primary/Documents/ doc/Bib/

# Then, we push changes from our machine to the tablet, deleting anything that
# doesn't exist in the computer anylonger
$VSR_ROOT/config/android/adb-sync --delete doc/Bib/ storage/self/primary/Documents
