#! /bin/bash

vsr_root="${BASH_SOURCE%/*}.."
source "$vsr_root/prelude"

function print_usage() {
  echo "sys-ufw-killswitch [start|stop]"
}

if [[ $# -ne "1" ]]; then
  print_usage
  exit 1
else
  opt=$1
  if [[ $opt == "start" ]]; then
    sudo ufw reset
    sudo ufw default deny incoming
    sudo ufw default deny outgoing
    sudo ufw allow out on tun0 from any to any
    sudo ufw allow in  on tun0 from any to any
    sudo ufw enable
    echo "Killswitch is on"
  elif [[ $opt == "stop" ]]; then
    sudo ufw reset
    vsr-ufw
    echo "Killswitch is off"
  else
    echo "Unknown option"
    print_usage
    exit 1
  fi
fi

