#! /bin/bash

vsr_root="${BASH_SOURCE%/*}/.."
source "$vsr_root/prelude"

function print_usage() {
  errcho "usage: vsr-unison [unison profile]"
  errcho ""
  errcho "  runs our magic unison, either on all"
  errcho "  proviles or on a single one"
  errcho ""
  exit 1
}

## First, we open the containers in the
## remote machine:
echo "We will connect to the remove host and open our luksContainer"
echo "You will need sudo ON THE REMOTE SERVER; get your passwords ready! :)"
ssh -t vps '/home/victor/openContainer.sh'

## The profiles that I like to enforce sync
allprofs=( "keychain" "doc" )

if [[ "$#" -eq "1" ]]; then
  allprofs=( "$1" )
elif [[ "$#" -gt "1" ]]; then
  print_usage
fi

for prof in ${allprofs[*]}; do
  unison $prof
done


ssh -t vps '/home/victor/closeContainer.sh'
