#!/bin/bash

set -o pipefail

entries="⏻ Shutdown\n⇠ Logout\n⭮ Reboot\n⏾ Suspend"
confirm=" ⃠  Abort\n✔ Confirm" 

function ask() {
  echo -e $1 |\
    wofi -i --height 230 --width 250 --dmenu --cache-file /dev/null |\
    awk '{print tolower($2)}'
}

function main() {
  option=$(ask "${entries}")
  if [ "$?" -eq "0" ]; then
    sure=$(ask "${confirm}")
    if [ "$?" -eq "0" ] && [[ "$sure" == "confirm" ]]; then
      case $option in
        logout)
          swaymsg exit;;
        suspend)
          exec systemctl suspend;;
        reboot)
          exec systemctl reboot;;
        shutdown)
          exec systemctl poweroff -i;;
      esac
    fi
  fi
}

main
